# Generated by Django 3.1 on 2025-08-24 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0003_auto_20250824_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descrição', models.TextField(blank=True, max_length=500)),
                ('preço', models.IntegerField()),
                ('imagens', models.ImageField(upload_to='photos/products')),
                ('quantidade', models.IntegerField()),
                ('esta_disponível', models.BooleanField(default=True)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('data_modificação', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
    ]
