# Generated by Django 4.2.24 on 2025-10-07 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('descrição', models.TextField(blank=True, max_length=500)),
                ('preço', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagens', models.ImageField(upload_to='photos/products')),
                ('quantidade', models.IntegerField()),
                ('esta_disponível', models.BooleanField(default=True)),
                ('data_criação', models.DateTimeField(auto_now_add=True)),
                ('data_modificação', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Variação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variação_categoria', models.CharField(choices=[('cor', 'cor'), ('tamanho', 'tamanho')], max_length=100)),
                ('valor_variação', models.CharField(max_length=100)),
                ('esta_ativo', models.BooleanField(default=True)),
                ('data_criação', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
        migrations.CreateModel(
            name='NotaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assunto', models.CharField(blank=True, max_length=100)),
                ('avaliação', models.TextField(blank=True, max_length=500)),
                ('nota', models.FloatField()),
                ('ip', models.CharField(blank=True, max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('atualizada_em', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
                ('usuário', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GaleriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(max_length=255, upload_to='loja/produtos')),
                ('produto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
