# Generated by Django 3.1 on 2025-08-27 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preço',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Variação',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variação_categoria', models.CharField(choices=[('cor', 'cor'), ('tamanho', 'tamanho')], max_length=100)),
                ('valor_variação', models.CharField(max_length=100)),
                ('esta_ativo', models.BooleanField(default=True)),
                ('data_criação', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
