# Generated by Django 4.2.24 on 2025-09-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_alter_produto_id_alter_variação_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preço',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
