# Generated by Django 4.2.24 on 2025-10-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('descrição', models.TextField(blank=True, max_length=255)),
                ('imagem_cat', models.ImageField(blank=True, upload_to='photos/categorias')),
            ],
        ),
    ]
