# Generated by Django 3.1 on 2025-08-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categria', models.CharField(max_length=50, unique=True)),
                ('slug', models.CharField(max_length=100, unique=True)),
                ('descrição', models.TextField(blank=True, max_length=255)),
                ('imagem_cat', models.ImageField(blank=True, upload_to='photos/categorias')),
            ],
        ),
    ]
