# Generated by Django 3.1 on 2025-08-24 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_auto_20250824_0117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_categria',
            new_name='nome_categoria',
        ),
    ]
