# Generated by Django 3.1 on 2025-08-28 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_auto_20250827_2034'),
        ('carrinho', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinhoitem',
            name='variações',
            field=models.ManyToManyField(blank=True, to='loja.Variação'),
        ),
    ]
