# Generated by Django 4.2.24 on 2025-09-19 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtopedido',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='produtopedido',
            name='tamanho',
        ),
    ]
