# Generated by Django 4.2.24 on 2025-09-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_produto_preço'),
        ('pedidos', '0002_remove_produtopedido_cor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtopedido',
            name='variação',
        ),
        migrations.AddField(
            model_name='produtopedido',
            name='variações',
            field=models.ManyToManyField(blank=True, to='loja.variação'),
        ),
    ]
