# Generated by Django 4.2.24 on 2025-09-20 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_remove_produtopedido_variação_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopedido',
            name='ordenado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produtopedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedido'),
        ),
    ]
