# Generated by Django 4.2.24 on 2025-09-29 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_notaavaliacao'),
        ('pedidos', '0004_produtopedido_ordenado_alter_produtopedido_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleriaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(max_length=255, upload_to='loja/produtos')),
                ('produto', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
