# Generated by Django 4.2.24 on 2025-09-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_galeriaproduto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GaleriaProduto',
        ),
    ]
