# Generated by Django 4.2.24 on 2025-10-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_delete_galeriaproduto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='rua',
            new_name='bairro',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cep',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='endereço',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
