# Generated by Django 4.2.24 on 2025-09-25 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_alter_conta_cpf_alter_conta_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(blank=True, max_length=100)),
                ('número', models.IntegerField()),
                ('foto_perfil', models.ImageField(blank=True, upload_to='userprofile')),
                ('cidade', models.CharField(blank=tuple, max_length=20)),
                ('estado', models.CharField(blank=tuple, max_length=20)),
                ('usuário', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
