# Generated by Django 4.2.24 on 2025-09-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='cidade',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='estado',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='número',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
