# Generated by Django 4.2.24 on 2025-10-05 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_perfilusuario_cidade_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='rua',
            new_name='endereço',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='bairro',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='cep',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
