# Generated by Django 4.2.24 on 2025-09-07 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loja', '0003_alter_produto_id_alter_variação_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrinho_id', models.CharField(blank=True, max_length=250)),
                ('data_criação', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarrinhoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('esta_ativo', models.BooleanField(default=True)),
                ('carrinho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carrinhos.carrinho')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
                ('usuário', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variações', models.ManyToManyField(blank=True, to='loja.variação')),
            ],
        ),
    ]
