# Generated by Django 4.2.24 on 2025-09-07 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrinhos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrinhoitem',
            name='usuário',
        ),
        migrations.AddField(
            model_name='carrinhoitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
