# Generated by Django 4.2.24 on 2025-09-07 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinhos', '0002_remove_carrinhoitem_usuário_carrinhoitem_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrinhoitem',
            old_name='user',
            new_name='usuário',
        ),
    ]
